/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "bbip_constants.h"

namespace bilibili {

const bbipConstants g_bbip_constants;

bbipConstants::bbipConstants() {
}

} // namespace

