/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef bbip_CONSTANTS_H
#define bbip_CONSTANTS_H

#include "bbip_types.h"

namespace bilibili {

class bbipConstants {
 public:
  bbipConstants();

};

extern const bbipConstants g_bbip_constants;

} // namespace

#endif
