// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "bbip.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::bilibili;

class bbipHandler : virtual public bbipIf {
 public:
  bbipHandler() {
    // Your initialization goes here
  }

  /**
   * A method definition looks like C code. It has a return type, arguments,
   * and optionally a list of exceptions that it may throw. Note that argument
   * lists and exception lists are specified using the exact same syntax as
   * field lists in struct or exception definitions.
   */
  void ping() {
    // Your implementation goes here
    printf("ping\n");
  }

  int32_t count() {
    // Your implementation goes here
    printf("count\n");
  }

  void query(bbip_result& _return, const std::string& string_ip) {
    // Your implementation goes here
    printf("query\n");
  }

  void query_string(std::string& _return, const std::string& string_ip) {
    // Your implementation goes here
    printf("query_string\n");
  }

  int16_t GetAreaFlag(const std::string& string_ip) {
    // Your implementation goes here
    printf("GetAreaFlag\n");
  }

  int64_t GetZoneID(const std::string& string_ip) {
    // Your implementation goes here
    printf("GetZoneID\n");
  }

  void query_long(bbip_result& _return, const int64_t int_ip) {
    // Your implementation goes here
    printf("query_long\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<bbipHandler> handler(new bbipHandler());
  shared_ptr<TProcessor> processor(new bbipProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

